/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/calendar-service-api';
export * from './apis/error-service-api';
export * from './apis/file-service-api';
export * from './apis/group-service-api';
export * from './apis/info-service-api';
export * from './apis/net-test-service-api';
export * from './apis/recording-service-api';
export * from './apis/room-service-api';
export * from './apis/user-service-api';
export * from './apis/wb-service-api';

