/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * Integration API enables to connect to an OpenMeetings instance, eg for generating users, create links to directly access conference rooms.<br/><br/>         <b>It is mainly designed for Server2Server integration, for example to integrate into your website, CMS or 3rd party application</b><br/><br/>         For examples how to use the Rest API see <a href=\"https://openmeetings.apache.org/RestAPISample.html\" target=\"_BLANK\">https://openmeetings.apache.org/RestAPISample.html</a>.<br/><br/>         Community contributed modules for using this API include for example:         <ul>          <li><a href=\"https://openmeetings.apache.org/RestAPISample.html#how-to-integrate-using-nodejs\" target=\"_BLANK\"> Node.js module for using API</a></li>         </ul>         Other community plugins using this API for Moodle, SugarCRM, Drupal, Joomla can be found in the Configuration>Plugins section at <a href=\"https://openmeetings.apache.org\" target=\"_BLANK\">https://openmeetings.apache.org</a>
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    additionalname?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    comment?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    country?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    deleted?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    fax?: any;
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof Address
     */
    inserted?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    phone?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    street?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    town?: any;
    /**
     * 
     * @type {Date}
     * @memberof Address
     */
    updated?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    zip?: any;
}
