/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    additionalname?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    comment?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    country?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    deleted?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    fax?: any;
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof Address
     */
    inserted?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    phone?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    street?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    town?: any;
    /**
     * 
     * @type {Date}
     * @memberof Address
     */
    updated?: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    zip?: any;
}
