/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AppointmentDTO
 */
export interface AppointmentDTO {
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentDTO
     */
    connectedEvent?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentDTO
     */
    deleted?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    description?: any;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentDTO
     */
    end?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    icalId?: any;
    /**
     * 
     * @type {number}
     * @memberof AppointmentDTO
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentDTO
     */
    inserted?: any;
    /**
     * 
     * @type {number}
     * @memberof AppointmentDTO
     */
    languageId?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    location?: any;
    /**
     * 
     * @type {Array&lt;MeetingMemberDTO&gt;}
     * @memberof AppointmentDTO
     */
    meetingMembers?: any;
    /**
     * 
     * @type {UserDTO}
     * @memberof AppointmentDTO
     */
    owner?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    password?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentDTO
     */
    passwordProtected?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    reminder?: AppointmentDTOReminderEnum;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentDTO
     */
    reminderEmailSend?: any;
    /**
     * 
     * @type {RoomDTO}
     * @memberof AppointmentDTO
     */
    room?: any;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentDTO
     */
    start?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    title?: any;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentDTO
     */
    updated?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum AppointmentDTOReminderEnum {
    NONE = 'NONE',
    EMAIL = 'EMAIL',
    ICAL = 'ICAL'
}

