/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * Integration API enables to connect to an OpenMeetings instance, eg for generating users, create links to directly access conference rooms.<br/><br/>         <b>It is mainly designed for Server2Server integration, for example to integrate into your website, CMS or 3rd party application</b><br/><br/>         For examples how to use the Rest API see <a href=\"https://openmeetings.apache.org/RestAPISample.html\" target=\"_BLANK\">https://openmeetings.apache.org/RestAPISample.html</a>.<br/><br/>         Community contributed modules for using this API include for example:         <ul>          <li><a href=\"https://openmeetings.apache.org/RestAPISample.html#how-to-integrate-using-nodejs\" target=\"_BLANK\"> Node.js module for using API</a></li>         </ul>         Other community plugins using this API for Moodle, SugarCRM, Drupal, Joomla can be found in the Configuration>Plugins section at <a href=\"https://openmeetings.apache.org\" target=\"_BLANK\">https://openmeetings.apache.org</a>
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AppointmentDTO
 */
export interface AppointmentDTO {
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentDTO
     */
    connectedEvent?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentDTO
     */
    deleted?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    description?: any;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentDTO
     */
    end?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    icalId?: any;
    /**
     * 
     * @type {number}
     * @memberof AppointmentDTO
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentDTO
     */
    inserted?: any;
    /**
     * 
     * @type {number}
     * @memberof AppointmentDTO
     */
    languageId?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    location?: any;
    /**
     * 
     * @type {Array&lt;MeetingMemberDTO&gt;}
     * @memberof AppointmentDTO
     */
    meetingMembers?: any;
    /**
     * 
     * @type {UserDTO}
     * @memberof AppointmentDTO
     */
    owner?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    password?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentDTO
     */
    passwordProtected?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    reminder?: AppointmentDTOReminderEnum;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentDTO
     */
    reminderEmailSend?: any;
    /**
     * 
     * @type {RoomDTO}
     * @memberof AppointmentDTO
     */
    room?: any;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentDTO
     */
    start?: any;
    /**
     * 
     * @type {string}
     * @memberof AppointmentDTO
     */
    title?: any;
    /**
     * 
     * @type {Date}
     * @memberof AppointmentDTO
     */
    updated?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum AppointmentDTOReminderEnum {
    NONE = 'NONE',
    EMAIL = 'EMAIL',
    ICAL = 'ICAL'
}

