/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExternalUserDTO
 */
export interface ExternalUserDTO {
    /**
     * 
     * @type {string}
     * @memberof ExternalUserDTO
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalUserDTO
     */
    externalId?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalUserDTO
     */
    externalType?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalUserDTO
     */
    firstname?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalUserDTO
     */
    lastname?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalUserDTO
     */
    login?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalUserDTO
     */
    profilePictureUrl?: any;
}
