/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FileItemDTO
 */
export interface FileItemDTO {
    /**
     * 
     * @type {string}
     * @memberof FileItemDTO
     */
    externalId?: any;
    /**
     * 
     * @type {string}
     * @memberof FileItemDTO
     */
    externalType?: any;
    /**
     * 
     * @type {number}
     * @memberof FileItemDTO
     */
    groupId?: any;
    /**
     * 
     * @type {string}
     * @memberof FileItemDTO
     */
    hash?: any;
    /**
     * 
     * @type {number}
     * @memberof FileItemDTO
     */
    height?: any;
    /**
     * 
     * @type {number}
     * @memberof FileItemDTO
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof FileItemDTO
     */
    name?: any;
    /**
     * 
     * @type {number}
     * @memberof FileItemDTO
     */
    ownerId?: any;
    /**
     * 
     * @type {number}
     * @memberof FileItemDTO
     */
    parentId?: any;
    /**
     * 
     * @type {number}
     * @memberof FileItemDTO
     */
    roomId?: any;
    /**
     * 
     * @type {number}
     * @memberof FileItemDTO
     */
    size?: any;
    /**
     * 
     * @type {string}
     * @memberof FileItemDTO
     */
    type?: FileItemDTOTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof FileItemDTO
     */
    width?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum FileItemDTOTypeEnum {
    FOLDER = 'FOLDER',
    IMAGE = 'IMAGE',
    POLLCHART = 'POLL_CHART',
    PRESENTATION = 'PRESENTATION',
    RECORDING = 'RECORDING',
    VIDEO = 'VIDEO',
    WMLFILE = 'WML_FILE'
}

