/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FileExplorerObject
 */
export interface FileExplorerObject {
    /**
     * 
     * @type {Array&lt;FileItemDTO&gt;}
     * @memberof FileExplorerObject
     */
    roomHome?: any;
    /**
     * 
     * @type {number}
     * @memberof FileExplorerObject
     */
    roomHomeSize?: any;
    /**
     * 
     * @type {Array&lt;FileItemDTO&gt;}
     * @memberof FileExplorerObject
     */
    userHome?: any;
    /**
     * 
     * @type {number}
     * @memberof FileExplorerObject
     */
    userHomeSize?: any;
}
