/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Health
 */
export interface Health {
    /**
     * 
     * @type {boolean}
     * @memberof Health
     */
    dbOk?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Health
     */
    inited?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Health
     */
    installed?: any;
}
