/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RecordingDTO
 */
export interface RecordingDTO {
    /**
     * 
     * @type {Date}
     * @memberof RecordingDTO
     */
    end?: any;
    /**
     * 
     * @type {string}
     * @memberof RecordingDTO
     */
    externalType?: any;
    /**
     * 
     * @type {string}
     * @memberof RecordingDTO
     */
    hash?: any;
    /**
     * 
     * @type {number}
     * @memberof RecordingDTO
     */
    height?: any;
    /**
     * 
     * @type {number}
     * @memberof RecordingDTO
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RecordingDTO
     */
    interview?: any;
    /**
     * 
     * @type {string}
     * @memberof RecordingDTO
     */
    name?: any;
    /**
     * 
     * @type {number}
     * @memberof RecordingDTO
     */
    ownerId?: any;
    /**
     * 
     * @type {number}
     * @memberof RecordingDTO
     */
    roomId?: any;
    /**
     * 
     * @type {Date}
     * @memberof RecordingDTO
     */
    start?: any;
    /**
     * 
     * @type {string}
     * @memberof RecordingDTO
     */
    status?: any;
    /**
     * 
     * @type {number}
     * @memberof RecordingDTO
     */
    width?: any;
}
