/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RoomOptionsDTO
 */
export interface RoomOptionsDTO {
    /**
     * 
     * @type {boolean}
     * @memberof RoomOptionsDTO
     */
    allowRecording?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomOptionsDTO
     */
    allowSameURLMultipleTimes?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomOptionsDTO
     */
    externalRoomId?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomOptionsDTO
     */
    externalType?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomOptionsDTO
     */
    moderator?: any;
    /**
     * 
     * @type {number}
     * @memberof RoomOptionsDTO
     */
    recordingId?: any;
    /**
     * 
     * @type {number}
     * @memberof RoomOptionsDTO
     */
    roomId?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomOptionsDTO
     */
    showAudioVideoTest?: any;
}
