/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * Integration API enables to connect to an OpenMeetings instance, eg for generating users, create links to directly access conference rooms.<br/><br/>         <b>It is mainly designed for Server2Server integration, for example to integrate into your website, CMS or 3rd party application</b><br/><br/>         For examples how to use the Rest API see <a href=\"https://openmeetings.apache.org/RestAPISample.html\" target=\"_BLANK\">https://openmeetings.apache.org/RestAPISample.html</a>.<br/><br/>         Community contributed modules for using this API include for example:         <ul>          <li><a href=\"https://openmeetings.apache.org/RestAPISample.html#how-to-integrate-using-nodejs\" target=\"_BLANK\"> Node.js module for using API</a></li>         </ul>         Other community plugins using this API for Moodle, SugarCRM, Drupal, Joomla can be found in the Configuration>Plugins section at <a href=\"https://openmeetings.apache.org\" target=\"_BLANK\">https://openmeetings.apache.org</a>
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RoomDTO
 */
export interface RoomDTO {
    /**
     * 
     * @type {boolean}
     * @memberof RoomDTO
     */
    allowRecording?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomDTO
     */
    allowUserQuestions?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomDTO
     */
    appointment?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomDTO
     */
    audioOnly?: any;
    /**
     * 
     * @type {number}
     * @memberof RoomDTO
     */
    capacity?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomDTO
     */
    closed?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomDTO
     */
    comment?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomDTO
     */
    confno?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomDTO
     */
    demo?: any;
    /**
     * 
     * @type {number}
     * @memberof RoomDTO
     */
    demoTime?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomDTO
     */
    externalId?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomDTO
     */
    externalType?: any;
    /**
     * 
     * @type {Array&lt;RoomFileDTO&gt;}
     * @memberof RoomDTO
     */
    files?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof RoomDTO
     */
    hiddenElements?: Array<RoomDTOHiddenElementsEnum>;
    /**
     * 
     * @type {number}
     * @memberof RoomDTO
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomDTO
     */
    moderated?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomDTO
     */
    name?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomDTO
     */
    _public?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomDTO
     */
    redirectUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomDTO
     */
    tag?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomDTO
     */
    type?: RoomDTOTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof RoomDTO
     */
    waitModerator?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoomDTO
     */
    waitRecording?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum RoomDTOHiddenElementsEnum {
    TOPBAR = 'TOP_BAR',
    CHAT = 'CHAT',
    ACTIVITIES = 'ACTIVITIES',
    FILES = 'FILES',
    ACTIONMENU = 'ACTION_MENU',
    POLLMENU = 'POLL_MENU',
    SCREENSHARING = 'SCREEN_SHARING',
    WHITEBOARD = 'WHITEBOARD',
    MICROPHONESTATUS = 'MICROPHONE_STATUS',
    USERCOUNT = 'USER_COUNT'
}
/**
    * @export
    * @enum {string}
    */
export enum RoomDTOTypeEnum {
    CONFERENCE = 'CONFERENCE',
    PRESENTATION = 'PRESENTATION',
    INTERVIEW = 'INTERVIEW'
}

