/* tslint:disable */
/* eslint-disable */
/**
 * Apache OpenMeetings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
    /**
     * 
     * @type {Address}
     * @memberof UserDTO
     */
    address?: any;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    externalId?: any;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    externalType?: any;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    firstname?: any;
    /**
     * 
     * @type {number}
     * @memberof UserDTO
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof UserDTO
     */
    languageId?: any;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    lastname?: any;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    login?: any;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    password?: any;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    pictureUri?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof UserDTO
     */
    rights?: Array<UserDTORightsEnum>;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    timeZoneId?: any;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    type?: UserDTOTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UserDTORightsEnum {
    ADMIN = 'ADMIN',
    GROUPADMIN = 'GROUP_ADMIN',
    ADMINCONFIG = 'ADMIN_CONFIG',
    ADMINCONNECTIONS = 'ADMIN_CONNECTIONS',
    ADMINBACKUP = 'ADMIN_BACKUP',
    ADMINLABEL = 'ADMIN_LABEL',
    ROOM = 'ROOM',
    DASHBOARD = 'DASHBOARD',
    LOGIN = 'LOGIN',
    SOAP = 'SOAP'
}
/**
    * @export
    * @enum {string}
    */
export enum UserDTOTypeEnum {
    USER = 'USER',
    LDAP = 'LDAP',
    OAUTH = 'OAUTH',
    EXTERNAL = 'EXTERNAL',
    CONTACT = 'CONTACT'
}

